### ISSUE TITLE
Create Export functionality

### ISSUE THREAD

**Issue by PhilMFischer** [virtualsatellite/VirtualSatellite4-FreeCAD-mod#6]
- [x] Export dialog to select a location for export
- [x] Functionality to export the current design into the proper json format for virtual satellite

**Comment by JAmmermann-DLR** [comment]
For the export functionality I can think of the following approach:
- [ ] first, we have to be able to parse the FreeCAD objects into our classes, so they should implement a _read_from_freecad_ function
- [ ] every class that can be written to FreeCAD (probably except sheets) knows how to be written into json format, so it has a _write_to_json_ function that returns a python dictionary representing the object
- [ ] (at some point we have to differ if a FreeCAD object is a part or a product: this could be done over the source file name, but maybe we should also add the identifiers into the object name)
- [ ] the exporter then would look like this: 

  ~~~~
  filter active document: only objects that have a sheet
  
  for part_ in active_doc:
    part = AJsonPart().read_from_freecad()
    parts.append(part.write_to_json())
  for assembly_ in active_doc:
    root_product = JsonProductAssembly().read_from_freecad()
    products = root_product.write_to_json()
  ~~~~
  and in JsonProductAssembly().write_to_json() check for subassemblies and also parse them like above

**Comment by JAmmermann-DLR** [comment]
Some shapes couldn't be tested, because they are missing in the importer too
Opened https://github.com/virtualsatellite/VirtualSatellite4-FreeCAD-mod/issues/20 for this issue
